import Footer from "../components/Footer";
import NavBar from "../components/NavBar";
import getCurrentUser from "./actions/getCurrentUser";
import "./globals.css";

export const metadata = {
  title: "Tukar-Menukar",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className="flex flex-col font-mono min-h-screen max-w-screen-sm mx-auto">
        <NavBar currentUser={currentUser} />
        <div className="flex-grow p-5 bg-gray-50">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
