import { Suspense } from "react";
import NavBar from "../components/NavBar";
import getCurrentUser from "./actions/getCurrentUser";
import "./globals.css";
import Loading from "./loading";

export const metadata = {
  title: "Tukar-Menukar",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body>
        <NavBar currentUser={currentUser} />
        {children}
      </body>
    </html>
  );
}
